project:
  type: website
  output-dir: docs

website:
  title: "PREVEU"
  navbar:
    logo: images/PREVEU-logo-blanc.png
    logo-alt: "Logo PREVEU"
    logo-width: 800
    left:
      - href: index.qmd
        text: Inici
      - href: qui-som.qmd
        text: Qui som
      - href: planificacio.qmd
        text: Planificació
      - href: activitats.qmd
        text: Activitats realitzades
      - href: resultats.qmd
        text: Resultats
      - href: adhereix-te.qmd
        text: Adhereix-te
      - href: contacte.qmd
        text: Contacte
    right:
      - text: "VA"
        href: index.qmd
      - text: "ES"
        href: es/index.qmd
      - text: "EN"
        href: en/index.qmd
  page-footer:
    left: "Projecte d'Innovació Educativa Emergent PREVEU [3897161] · Universitat de València"
    right: "© 2025"

format:
  html:
    theme: flatly
    css: styles.css
    toc: false
